### ISSUE TITLE
Cron URl error

### ISSUE THREAD

**Issue by mark-chief** [Goldinteractive/craft3-publisher#1]
HI,

When I hit the url https://www.domain.com/actions/publisher/api/publish I get the Internal Server error, Am i doing something wrong? I have an entry that is published already, with a new draft, see attachment and error below. Thanks!!

```
2019-03-15 12:48:33 [-][1][ro1c9ug2iffc7bnevqrov37741][error][TypeError] TypeError: Return value of goldinteractive\publisher\elements\EntryPublish::getEntry() must be an instance of craft\elements\Entry, null returned in /home/runcloud/webapps/projectname/craft/vendor/goldinteractive/craft3-publisher/src/elements/EntryPublish.php:163
Stack trace:
#0 /home/runcloud/webapps/projectname/craft/vendor/goldinteractive/craft3-publisher/src/services/Entries.php(57): goldinteractive\publisher\elements\EntryPublish->getEntry()
#1 /home/runcloud/webapps/projectname/craft/vendor/goldinteractive/craft3-publisher/src/controllers/ApiController.php(34): goldinteractive\publisher\services\Entries->publishDueEntries()
#2 [internal function]: goldinteractive\publisher\controllers\ApiController->actionPublish()
#3 /home/runcloud/webapps/projectname/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/runcloud/webapps/projectname/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /home/runcloud/webapps/projectname/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('publish', Array)
#6 /home/runcloud/webapps/projectname/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('publish', Array)
#7 /home/runcloud/webapps/projectname/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('publisher/api/p...', Array)
#8 /home/runcloud/webapps/projectname/craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('publisher/api/p...', Array)
#9 /home/runcloud/webapps/projectname/craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /home/runcloud/webapps/projectname/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /home/runcloud/webapps/projectname/craft/public/index.php(21): yii\base\Application->run()
#12 {main}
2019-03-15 12:48:33 [-][1][ro1c9ug2iffc7bnevqrov37741][info][application] $_GET = [
    'p' => 'actions/publisher/api/publish'
]

```

<img width="323" alt="Screen Shot 2019-03-15 at 13 00 33" src="https://user-images.githubusercontent.com/18699249/54432824-2d8a2880-4722-11e9-8f1e-981b646d61e8.png">

**Comment by christianruhstaller** [comment]
This shouldn't happen. I updated the function so that it can return null. That means this error should not happen anymore. But it will break some lines below because the entry is null, which it shouldn't be.

It would be interesting to see what is in the database for the publisher (entrypublishes) and if the entryId is null and if not if the ID does really exist as an entry.
